[connections.oracle_onprem_db]
url= "oracle+oracledb://scott:tiger@localhost:1521?service_name=FREEPDB1"


[connections.oci_cloud_db]
url= "oracle+oracledb://scott:Skp123456789@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=36540ca34702_streamdb_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))"
